# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
name: hony

services:
  honyapi:
    image: honyapi
    build:
      context: .
      dockerfile: src/Hony.Api/Dockerfile
      args:
        - configuration=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=honymon
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/hony.pfx
      - ASPNETCORE_URLS=https://+:8080;http://+:8081
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
    develop:
      watch:
        - path: .
          action: rebuild