name: hony

services:
  honyapi:
    image: honyapi:v1
    container_name: honyapi-mix
    build:
      context: .
      dockerfile: src/Hony.Api/Dockerfile
    restart: always
    environment:
      - POST_CONNECTION=server=192.168.0.3;port=5432;user id=${PUSER};password=${PPASS};database=${PDATA};
      - MONG_CONNECTION=mongodb://${PUSER}:${PPASS}@192.168.0.5:27017
      - JWT_KEY=${JTKEY}
    ports:
      - 7005:7005
    networks:
      hony:
        ipv4_address:  192.168.0.1
    depends_on:
      - honyapi.db.service
      - honyapi.db.tokens
  honyweb:
    container_name: honyweb-mix
    image: honyweb:v1
    build:
      context: .
      dockerfile: src/Hony.Web/Dockerfile
    restart: always
    ports:
      - 7007:7007
    networks:
      hony:
        ipv4_address:  192.168.0.2
    depends_on:
      - honyapi
  honyapi.db.service:
    image: postgres
    container_name: honyapi-postgres
    environment:
      - POSTGRES_USER=${PUSER}
      - POSTGRES_PASSWORD=${PPASS}
      - POSTGRES_DB=${PDATA}
    expose:
      - 5432
    ports:
      - 7008:5432
    networks:
      hony:
        ipv4_address:  192.168.0.3
    volumes:
      - hony:/var/lib/postgresy
  honyapi.db.tokens:
    image: mongo
    container_name: honyapi-mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${PPASS}
      - MONGO_INITDB_ROOT_USERNAME=${PUSER}
    expose:
      - 27017
    ports:
      - 7010:27017
    networks:
      hony:
        ipv4_address:  192.168.0.5
    volumes:
      - hony:/data/db
volumes:
  hony:
    external: false
networks:
  hony:
    external: false
    ipam:
      config:
        - subnet: 192.168.0.0/20
          gateway: 192.168.0.20