[33mcommit 6722c563df87d8881c85488874e2514c00db243a[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mdev[m[33m, [m[1;31morigin/dev[m[33m)[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Thu Jun 6 10:13:24 2024 -0400

    mod comments

[33mcommit 895eee2a1d6d250e558ccbd6053263b857de6031[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Thu Jun 6 10:08:36 2024 -0400

    create blog handler  and services

[33mcommit f130596e7bd7ec0324d595f4dc45092781852c7a[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Wed Jun 5 12:53:15 2024 -0400

    add jwt interceptor event

[33mcommit 956480467321627382e92fa4ff869c16f162ef94[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Wed Jun 5 08:51:48 2024 -0400

    add test and web project

[33mcommit c822aba408664903430ae432f09137ace7025889[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Wed Jun 5 07:17:53 2024 -0400

    delete test ptojects

[33mcommit 28612c89f5591462f51740339c729b40940f4cd8[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Tue Jun 4 16:27:07 2024 -0400

    create blog implementation in unit of word

[33mcommit c847454a848b403bd72f8b2b2a08aabbd98154ff[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Tue Jun 4 15:34:43 2024 -0400

    create blog entity and configuration context v1

[33mcommit 9ba0e845a7456d8598549f49f2719c2d682a2303[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Tue Jun 4 10:13:48 2024 -0400

    add validations in create account validation

[33mcommit 2e3f69ecae6a946bcf9267e7391627e2ab065c01[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Tue Jun 4 10:05:54 2024 -0400

    fixed authentication

[33mcommit a18bf766f2fb4e69b4dd3b731e15c699336ed89f[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Mon Jun 3 23:30:35 2024 -0400

    documentation by chatgpt and format project

[33mcommit 77befafd6fa972b2883ad5ebd2f0ff1c15977f78[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Mon Jun 3 22:22:39 2024 -0400

    create jwt services fixed

[33mcommit f8dcbd556720617cda373112e86ef22b07830f99[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Mon Jun 3 22:21:43 2024 -0400

    create jwt services and refresh token service

[33mcommit 797c431c4a07fa528c3489fd5c700d043b3e7d6d[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Sat Jun 1 20:46:15 2024 -0400

    create jwt generator feature

[33mcommit 9ed2c3314f2887b601bc3c50649a62a88fefa4ae[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Sat Jun 1 18:10:23 2024 -0400

    fixed https container ports and project structure

[33mcommit 8486e9b264d1353d7eda875c7ad880bef08389c6[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 21:57:32 2024 -0400

    create error middleware

[33mcommit 129a35a0c37c95a83c9fc8b2c430443df5bb0cf5[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 21:34:38 2024 -0400

    create user endpoint and fixed docker compose

[33mcommit 15f68de1dddce382c5c731c1b43ff024eb969408[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 19:01:41 2024 -0400

    create register handler

[33mcommit fa6910708a0f225bfa9d4111f20ef60649333ef6[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 16:20:14 2024 -0400

    mod repository

[33mcommit f1f85f0282a0bb62722e2ccf684cdab54aea58eb[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 16:19:17 2024 -0400

    create basic mapper

[33mcommit 8f38da01e9de7ddbe57e85a4d96accf7ac722d67[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 12:42:03 2024 -0400

    implement unit-of-word service

[33mcommit 369c4e41a1c62e7b20df973ee3df2d4e457c3d36[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 10:45:18 2024 -0400

    create repository v1 interfaces

[33mcommit 80a2099a617727ac53a6ebf670e2ca7fb5b57ee8[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 09:36:34 2024 -0400

    create handler interfaces

[33mcommit 6986db67a25e1dd616c194f58c85778ad9b19468[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 09:20:54 2024 -0400

    create migration v1

[33mcommit 7168c195947f4eb4d15678644080deff9dfc8c08[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 08:12:15 2024 -0400

    create context and configuration base

[33mcommit 7b8233e91420567f7b7f9f70abf6306f744c948a[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 07:33:07 2024 -0400

    create account model base v1

[33mcommit f757419aa9dbdb59f7d7cc1aa0e091e624ce5da7[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Fri May 31 07:02:29 2024 -0400

    create infra design

[33mcommit 54d389119bde31191ad7a517dfef834ecb2827d0[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Thu May 30 23:56:12 2024 -0400

    Create common  base entities

[33mcommit fbf8a89ba977e863bb1f28b36772022c3595f891[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Thu May 30 23:17:01 2024 -0400

    initial documentation

[33mcommit f27018b9d07fa9d2d64bc3f0e8c7f0a5b626fb5d[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Thu May 30 22:58:03 2024 -0400

    generate static mobs

[33mcommit cf8ab85e4891ff1d1f5f704a40b03743b8615811[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Thu May 30 22:31:39 2024 -0400

    add test projects

[33mcommit c091b4c69a957c3d6d4aec329daaa2a5843af83a[m
Author: Coollbreackerz <ralberinfante4@gmail.com>
Date:   Thu May 30 22:21:16 2024 -0400

    Template v1
